version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm install --save-dev @babel/cli@7.17.1
      - run: npm install --save-dev browser-sync@2.27.10
      - run: npm install --save-dev babel-jest@28.1.1
      - run: npm install --save-dev jest-cli@28.1.1
      - run: npm install --save-dev jest@28.1.1
      - run: npm install --save-dev node-sass@7.0.1
      - run: npm install --save-dev ajv@8.11.0
      - run: npm install --save-dev concurrently@7.2.2
      - run: npm install --save-dev open-cli@7.0.1
      - run: npm install --save-dev replace@1.2.1
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
        - run: npm install --save-dev @babel/cli@7.17.1
      - run: npm install --save-dev browser-sync@2.27.10
      - run: npm install --save-dev babel-jest@28.1.1
      - run: npm install --save-dev jest-cli@28.1.1
      - run: npm install --save-dev jest@28.1.1
      - run: npm install --save-dev node-sass@7.0.1
      - run: npm install --save-dev ajv@8.11.0
      - run: npm install --save-dev concurrently@7.2.2
      - run: npm install --save-dev open-cli@7.0.1
      - run: npm install --save-dev replace@1.2.1
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test